### ISSUE TITLE
general purpose buttons?

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/lesson-example#189]
There is a place in the R-gapminder-es lesson where the user is told that they can export an image by clicking on the "Export" button. 

Would it be appropriate to use <kbd>Export</kbd>  to make this more visible? See example PR.

**Comment by rgaiacs** [comment]
> [There is a place in the R-gapminder-es lesson](https://swcarpentry.github.io/r-novice-gapminder-es/11-writing-data/) where the user is told that they can export an image by clicking on the "Export" button.
>
> Would it be appropriate to use Export to make this more visible?

Based on our [Style Guide](http://swcarpentry.github.io/lesson-example/06-style-guide/index.html) we use the `<kbd>` for **keyboard key** instruction only to respect HTML semantic. For example, we should write

~~~
On Jupyter Notebook, to delete the cell press <kbd>D</kbd>
~~~

But

~~~
On Jupyter Notebook, type <kbd>x = 1</kbd>
~~~

would be wrong because "x = 1" isn't a key that the user would find in their keyboard. The previous example should be write as 

~~~
On Jupyter Notebook, type `x = 1`
~~~

Back to your suggestion, we can't use `<kbd>Export</kbd>`. We could use `<span class="rstudio-button">Export</span>` but this involve use HTML tags which will open the case to use HTML tags for other things. We can review our policy regards HTML tags any time but be aware that if we decide to use `<span>` for anything I will advocate to use `<section>` for our call out boxes.

**Comment by raynamharris** [comment]
Okay, thanks for the clarification @rgaiacs
