### ISSUE TITLE
Challenge with numbered list and code blocks doesn't number correctly

### ISSUE THREAD

**Issue by brendam** [swcarpentry/lesson-example#71]
In a challenge block with a numbered list of challenges the numbering restarts after a code block. Can work around by using a bulleted list instead. https://github.com/data-lessons/library-python/issues/8

**Comment by rgaiacs** [comment]
@brendam Thanks for the issue.

> In a challenge block with a numbered list of challenges the numbering restarts after a code block.

This happens because of Markdown files not well format. E.g.

~~~
$ cat bug.md 
> 1. foo
>
> ~~~
> 1 + 1
> ~~~
>
> 2. foo
>
> new
$ kramdown bug.md
<blockquote>
  <ol>
    <li>foo</li>
  </ol>

  <pre><code>1 + 1
</code></pre>

  <ol>
    <li>foo</li>
  </ol>

  <p>new</p>
</blockquote>
$ cat fix.md 
> 1.  foo
>
>     ~~~
>     1 + 1
>     ~~~
>
> 2.  foo
>
>     new
$ kramdown fix.md 
<blockquote>
  <ol>
    <li>
      <p>foo</p>

      <pre><code>1 + 1
</code></pre>
    </li>
    <li>
      <p>foo</p>

      <p>new</p>
    </li>
  </ol>
</blockquote>
~~~

Usually, the maintainers curate the Markdown files to ensure that they are well format and it is up to them to enforce or not the use of bullet list.

cc @k8hertweck
