### ISSUE TITLE
The "Contributing" link points to a Markdown file, not an HTML file

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [swcarpentry/lesson-example#77]
In the 

Source/Contributing/Contact 

trimuvirate in the footer of the pages, I realised, because I was viewing 
some pages offline, that it referred to 

```
file:///blob/gh-pages/CONTRIBUTING.md
```

so a dot-MD file inside the GitHub repo and not an HTML page,
created  within the ```_sites``` directory, even though the distribution
contains a ```CONTRIBUTING.md``` in the top-level directory which
is alongside a ```LICENSE.md``` that does get turned into an HTML 
page.

When one is viewing online, the link to the lesson's repository's blob
of the MD-file will automatically get presented as an HTML page but,
given the existence of the  ```CONTRIBUTING.md``` in the top-level 
directory, I thought to ask if it was the intention point to the blob, and
not an HTML file that could be created?

**Comment by rgaiacs** [comment]
@vuw-ecs-kevin Sorry for the delay to reply to you and thanks very much for this issue.

You get `file:///blob/gh-pages/CONTRIBUTING.md` because on

~~~
	<a href="{{ site.github.repository_url }}/blob/gh-pages/CONTRIBUTING.md">Contributing</a>
~~~

the variable `site.github.repository_url` is empty and you are viewing the file offline.
Unfortunately there is no good way to setup this variable properly. But the link works file on the online version.
